---
- name: Replace specific values in destination config file on Windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Define keys to update
      set_fact:
        keys_to_update:
          - BulkDownloadFolder 
          - DiscoveryClientmUploadDir 

    - name: Read specific key-value pairs from source config file
      win_shell: |
        $keys = '{{ keys_to_update | to_json }}' | ConvertFrom-Json
        $pairs = @()
        foreach ($key in $keys) {
          $value = Get-Content "D:\\trident\\trident04config.config" | Select-String -Pattern "<add key=`"$key`" value=`"(.*?)`"" | ForEach-Object { $_.Matches.Groups[1].Value }
          if ($value) {
            $pairs += [PSCustomObject]@{ Key = $key; Value = $value }
          }
        }
        # Output as a list of JSON objects for Ansible
        $pairs | ConvertTo-Json
      register: specific_key_value_pairs

    - name: Convert JSON output to list of dictionaries
      set_fact:
        specific_key_value_pairs_list: "{{ specific_key_value_pairs.stdout | from_json }}"

    - name: Check if specific key-value pairs were found in source config
      fail:
        msg: "No specific key-value pairs found in the source config file."
      when: specific_key_value_pairs_list | length == 0

    - name: Replace values for specific keys in destination config
      win_lineinfile:
        path: "D:\\artifact\\artifactconfig.config"
        regexp: '(?<=<add key="{{ item.Key }}" value=")[^"]*'
        line: "{{ item.Value }}"
        backrefs: yes
        state: present
      loop: "{{ specific_key_value_pairs_list }}"

    - name: Verify changes in destination file
      win_shell: Get-Content -Path "D:\\artifact\\artifactconfig.config"
      register: destination_config_content

    - debug:
        var: destination_config_content.stdout_lines