---
- name: Replace value for dtIndexesBasePath in destination config file on Windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Extract value from source config file
      win_shell: |
        Select-String -Path "D:\\trident\\trident04config.config" -Pattern '<add key="dtIndexesBasePath" value="(.*?)"' | ForEach-Object { $_.Matches.Groups[1].Value }
      register: discovery_client_ftp_value

    - name: Check if dtIndexesBasePath value was found in source config
      fail:
        msg: "The key 'dtIndexesBasePath' was not found in the source config file."
      when: discovery_client_ftp_value.stdout == ""

    - name: Replace value for dtIndexesBasePath in destination config
      win_lineinfile:
        path: "D:\\artifact\\artifactconfig.config"
        regexp: '(?<=<add key="dtIndexesBasePath" value=")[^"]*'
        line: "{{ discovery_client_ftp_value.stdout }}"
        backrefs: yes
        state: present

    - name: Verify changes in destination file
      win_shell: Get-Content -Path "D:\\artifact\\artifactconfig.config"
      register: destination_config_content

    - debug:
        var: destination_config_content.stdout_lines
